### ISSUE TITLE
Doesn't build on Linux

### ISSUE THREAD

**Issue by Manishearth** [integer32llc/rust-playground#265]
Installed the latest yarn, stuff seems broken.

```
[13:34:44] मanishearth@aperture ~/mozilla/playpen/ui/frontend ^_^ 
$ yarn
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
[########################################################################################-----------------------------------------------------] 477/[##########################################################################################---------------------------------------------------] 489/info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 19.06s.
[13:35:06] मanishearth@aperture ~/mozilla/playpen/ui/frontend ^_^ 
$ yarn run watch
yarn run v1.3.2

/home/manishearth/mozilla/playpen/ui/frontend/webpack.config.js:115
  );
  ^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at requireConfig (/home/manishearth/mozilla/playpen/ui/frontend/node_modules/webpack/bin/convert-argv.js:97:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by shepmaster** [comment]
"works for me"

It also successfully builds in Travis, so I'd be highly inclined to think this is a local issue.

Can you make sure the files appear to be correct? I'm at git commit 2def0d8aef0cee3a0ce041de656ddb8ccc60e441:

```
$ md5sum package.json webpack.config.js
09cd5dcfd22eb4c9ff22c8158974c77c  package.json
84c94b4e9fe4be522e7032d35d9f566f  webpack.config.js
```

Does the file actually look like malformed JS to you?

**Comment by Manishearth** [comment]
The checksums work.

I suspect it's a missing package. I'm using yarn 1.3.2.

**Comment by Manishearth** [comment]
Aha, installed the latest node and now it works.

(Please list node as a dependency ; as someone unaware of the Node ecosystem I assumed yarn would install the appropriate compiler as well)

**Comment by shepmaster** [comment]
You had Node installed, otherwise you couldn't have gotten a stack trace of any kind. What version of Node did you have?

**Comment by Manishearth** [comment]
probably the default distro one
