### ISSUE TITLE
Cannot read property '_handle' of undefined in production

### ISSUE THREAD

**Issue by shepmaster** [integer32llc/rust-playground#66]
```
vendor-f875c97….js:58 Uncaught TypeError: Cannot read property '_handle' of undefined
    at http://play.integer32.com/vendor-f875c976a9dab3b0e5f5.js:58:1525
    at Array.forEach (native)
    at e.exports (http://play.integer32.com/vendor-f875c976a9dab3b0e5f5.js:58:1504)
    at Object.<anonymous> (http://play.integer32.com/vendor-f875c976a9dab3b0e5f5.js:16:6124)
    at Object.<anonymous> (http://play.integer32.com/vendor-f875c976a9dab3b0e5f5.js:16:10942)
    at t (http://play.integer32.com/manifest-842991282bc80cd97f47.js:1:107)
    at Object.<anonymous> (http://play.integer32.com/vendor-f875c976a9dab3b0e5f5.js:27:22411)
    at Object.<anonymous> (http://play.integer32.com/vendor-f875c976a9dab3b0e5f5.js:27:24195)
    at t (http://play.integer32.com/manifest-842991282bc80cd97f47.js:1:107)
    at Object.<anonymous> (http://play.integer32.com/vendor-f875c976a9dab3b0e5f5.js:27:27240)
(anonymous) @ vendor-f875c97….js:58
e.exports @ vendor-f875c97….js:58
(anonymous) @ vendor-f875c97….js:16
(anonymous) @ vendor-f875c97….js:16
t @ manifest-8429912….js:1
(anonymous) @ vendor-f875c97….js:27
(anonymous) @ vendor-f875c97….js:27
t @ manifest-8429912….js:1
(anonymous) @ vendor-f875c97….js:27
(anonymous) @ vendor-f875c97….js:27
t @ manifest-8429912….js:1
(anonymous) @ vendor-f875c97….js:1
t @ manifest-8429912….js:1
window.webpackJsonp @ manifest-8429912….js:1
(anonymous) @ vendor-f875c97….js:1
```

**Comment by shepmaster** [comment]
Must have been a hiccup from switching to yarn. Can't reproduce.
